// layout.tsx or RootLayout.tsx
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/sessionProvider";
import "./globals.css";
import { FavoriteProvider } from "./context/FavoriteContext";
import { SearchProvider } from "./context/SearchContext"; // Import the SearchProvider
import { CartProvider } from "./context/CartContext"; // นำเข้า CartProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ECLAT",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo-notext.png", // Path to your logo image
  },
};

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <FavoriteProvider>
            <CartProvider> {/* เพิ่ม CartProvider */}
              <SearchProvider>{children}</SearchProvider>
            </CartProvider>
          </FavoriteProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
